<%@ Page Title="" Language="C#" MasterPageFile="~/IPS_Vertical.Master" AutoEventWireup="true" CodeBehind="User_Management.aspx.cs" Inherits="IPS_Prototype.User_Management" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <script>
        $(document).ready(function () {

        $('#dLabel + ul > li').click(function () {
            // Declare variables 
            var input, filter, table, tr, td, i;
            input = document.getElementById("dLabel");

            filter = input.innerText.toUpperCase();
            console.log("test", filter);
            table = document.getElementsByClassName("BlueTable");
            tr = $(".BlueTable").find('tr');

            if (filter != "ALL") {
                // Loop through all table rows, and hide those who don't match the search query
                for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[2];
                if (td) {
                        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                         tr[i].classList.remove("none");
                         tr[i].classList.add("next");
                        } else {
                         tr[i].classList.remove("next");
                         tr[i].classList.add("none");
                        }
                    }
                }
            }

            else {
                for (i = 0; i < tr.length; i++) {
                tr[i].classList.remove("next");
                tr[i].classList.remove("none");

                }
            }
        });
});
        
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
       <div id="UserAddSuccess" class="alert alert-success">
  <strong>Success!</strong> Successfully Deleted User: <label runat="server" id="AlertName">Name</label> UserPermission: <label runat="server" id="AlertPermissionLevel">UserLevel</label>.
    </div>
    <div id="UserAddFail" class="alert alert-danger">
  <strong>Unsuccessful!</strong> There seems to be an error! Please notify the Administrators.
    </div>
    <label class="title">Users</label>
   
          <div id="MemberSearch">
              <button type="button" class="btn btn-primary SearchIcon" id="UserSearchIcon"><i class="fas fa-search"></i></button>
              
              <div id="MemberHover">
              <input type="text" class="SearchTxtbox" id="UserSearchTxtbox"/>

               <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary dropdown-toggle customDropdown">ALL</a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                                    <li><a class="dropdown-item" href="#" id="MemberDropdownSelected">ALL</a></li>
                                    <li class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="#">SUPERADMIN</a></li>
                                    <li><a class="dropdown-item" href="#">EXECUTIVE</a></li>
                                    <li><a class="dropdown-item" href="#">STAFF</a></li>
                                    <li><a class="dropdown-item" href="#">TEMP</a></li>
                                    </ul>

              </div>
              <button type="button" runat="server" class="btn btn-primary right" id="UserAdd" onserverclick="UserAddClick"><i class="fas fa-plus"></i></button>
          </div>
        <div id="MemberContent">
        <asp:GridView runat="server" ID="UserTable" CssClass="table table-hover BlueTable" AutoGenerateColumns="false" AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" GridLines="None" UseAccessibleHeader="true" BorderStyle="None" OnRowEditing="UserTable_RowEditing" OnRowDeleting="UserTable_RowDeleting">
           <Columns>
               <asp:BoundField DataField="Full_Name" HeaderText="Name" />
               
               <asp:BoundField DataField="Email_Addr" HeaderText="Email"/>
               <asp:BoundField DataField="Role_Type" HeaderText="Role" />
               <asp:BoundField DataField="User_Name" HeaderText="UserID" />
               <asp:BoundField DataField="Modified_Date" HeaderText="Last Modified" />
               <asp:BoundField DataField="Created_Date" HeaderText="Created" />
               
               <asp:CommandField EditText="Edit" ShowEditButton="true"/>
               <asp:CommandField DeleteText="Delete" ShowDeleteButton="true"/>
           </Columns>
        </asp:GridView>
     
   </div>
    
    
</asp:Content>
